version: '3'

services: 

    server:
        build: .
        env_file: .env
        ports: 
            - ${APP_PORT}:${APP_PORT}
        volumes:
            - "./data:/app/data"
        depends_on: 
            - database

    database:
        image: mongo:latest
        env_file: .env
        ports: 
            - ${DB_PORT}:${DB_PORT}
        volumes: 
            - db-data:/data/db

volumes: 
    db-data:
